[tasks.build]
dependencies = ["build-srv", "build-front"]

[tasks.build-srv]
command = "cargo"
args = ["build"]

[tasks.build-front]
dependencies = [
	{ name = "build", path = "ui" },
]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["build"]

[tasks.ci]
dependencies = [
	{ name = "install", path = "ui" },
	"build"
]
